### ISSUE TITLE
Error with network tiles and level change

### ISSUE THREAD

**Issue by rzzzwilson** [rzzzwilson/pySlipQt#1]
Changing up in levels quickly gets an exception:

> Traceback (most recent call last):
>   File "/Users/r-w/git/pySlipQt/pyslipqt/pyslipqt.py", line 128, in paintEvent
>     self.tile_src.GetTile(x, y))
>   File "/Users/r-w/git/pySlipQt/pyslipqt/tiles_net.py", line 313, in GetTile
>     tile_date = self.cache.tile_date((self.level, x, y))
>   File "/Users/r-w/git/pySlipQt/pyslipqt/tiles.py", line 52, in tile_date
>     return os.path.getctime(tile_path)
>   File "/Users/r-w/VirtEnv/work/bin/../lib/python3.6/genericpath.py", line 65, in getctime
>     return os.stat(filename).st_ctime
> FileNotFoundError: [Errno 2] No such file or directory: './osm_tiles/6/0/1.png'

The tile actually is there after the exception, so this is possibly because we try to get the date and the tile hasn't yet arrived from the 'net.  That means we are probably calling GetTile() twice and the second call crashes?  If we are slow to go down a level, no problem.

**Comment by rzzzwilson** [comment]
Commented out code in "tiles_net.py", around line 314;

```
#            tile_date = self.cache.tile_date((self.level, x, y))
#            if self.rerequest_age and (tile_date < self.rerequest_age):
#                self.get_server_tile(self.level, x, y)
```

The error now doesn't manifest, but uncommenting brings it back.  Error probably occurs when we try to get a non-existing tile: we start the 'net retrieval process, place the "pending" tile into the in-memory cache but not on-disk cache, and return the "pending" image.  The *next* call to GetTile() will return the in-memory "pending" tile and then any attempt to get the date of the tile on disk errors as the 'net tile hasn't come back yet so there's nothing in the on-disk cache.
