### ISSUE TITLE
Zooming out sometimes gets error

### ISSUE THREAD

**Issue by rzzzwilson** [rzzzwilson/pySlipQt#12]
When zooming out (quickly?) we get this exception:

    Traceback (most recent call last):
      File "/Users/r-w/git/pySlipQt/pyslipqt/tiles.py", line 202, in GetTile
        return self.cache[(self.level, x, y)]
      File "/Users/r-w/git/pySlipQt/pyslipqt/pycacheback.py", line 28, in __getitem__
        value = self._get_from_back(key)
      File "/Users/r-w/git/pySlipQt/pyslipqt/tiles.py", line 77, in _get_from_back
        % str(key))
    KeyError: "Item with key '(0, 0, 1)' not found in on-disk cache"

**Comment by rzzzwilson** [comment]
It's not caused by *speed* of zooming, but trying to zoom out from the top-most level!

**Comment by rzzzwilson** [comment]
After fiddling with zoom and drag *without* wrap, can't reproduce this problem.
