### ISSUE TITLE
Crash when changing tiles to BlueMarble

### ISSUE THREAD

**Issue by rzzzwilson** [rzzzwilson/pySlipQt#23]
When displaying OSM tiles, level 4 at geo position (0, 0), changing to BlueMarble tiles gets this:

```
Uncaught exception:
Traceback (most recent call last):
  File "/Users/r-w/git/pySlipQt/pyslipqt/tiles_net.py", line 115, in run
    self.callback(level, x, y, pixmap, error)
  File "/Users/r-w/git/pySlipQt/pyslipqt/tiles_net.py", line 414, in tile_is_available
    self.callback()
TypeError: OnTileAvailable() missing 5 required positional arguments: 'level', 'x', 'y', 'img', and 'bmp'

```

**Comment by rzzzwilson** [comment]
Fixed, missing code?
