### ISSUE TITLE
test_gotoposition.py strange error

### ISSUE THREAD

**Issue by rzzzwilson** [rzzzwilson/pySlipQt#38]
When running *test_gotoposition.py* and doing a zoom, we get this strange error:

```
================================================================================
Uncaught exception:
Traceback (most recent call last):
  File "/Users/r-w/VirtEnv/work/lib/python3.7/site-packages/pySlipQt-0.1.7-py3.7.egg/pySlipQt/tiles_net.py", line 115, in run
    self.callback(level, x, y, pixmap, error)
  File "/Users/r-w/VirtEnv/work/lib/python3.7/site-packages/pySlipQt-0.1.7-py3.7.egg/pySlipQt/tiles_net.py", line 410, in tile_is_available
    self.callback(level, x, y, image, True)
TypeError: arguments did not match any overloaded call:
  update(self): too many arguments
  update(self, QRect): argument 1 has unexpected type 'int'
  update(self, QRegion): argument 1 has unexpected type 'int'
  update(self, int, int, int, int): argument 4 has unexpected type 'QPixmap'
================================================================================

QObject::~QObject: Timers cannot be stopped from another thread
```

Why is this simple test program failing in this way?  Could be related to the general flakiness of the *goto*()* functions.

**Comment by rzzzwilson** [comment]
Problem can't be reproduced after implementing *GotoPosition()* code.
