### ISSUE TITLE
BUG in test_gmt_local_tiles.py

### ISSUE THREAD

**Issue by rzzzwilson** [rzzzwilson/pySlipQt#45]
```
$ python3 test_gmt_local_tiles.py
EE
======================================================================
ERROR: testErrors (__main__.TestGMTTiles)
Test possible errors.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gmt_local_tiles.py", line 74, in testErrors
    cache = tiles.Tiles()
  File "/usr/local/lib/python3.6/dist-packages/pySlipQt-0.5.1-py3.6.egg/pySlipQt/gmt_local.py", line 103, in __init__
    self.ppd_x, self.ppd_y) = self.GetInfo(self.level)
TypeError: 'NoneType' object is not iterable

======================================================================
ERROR: testSimple (__main__.TestGMTTiles)
Simple tests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gmt_local_tiles.py", line 53, in testSimple
    cache = tiles.Tiles()
  File "/usr/local/lib/python3.6/dist-packages/pySlipQt-0.5.1-py3.6.egg/pySlipQt/gmt_local.py", line 103, in __init__
    self.ppd_x, self.ppd_y) = self.GetInfo(self.level)
TypeError: 'NoneType' object is not iterable

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=2)

```

**Comment by rzzzwilson** [comment]
This was due to the GMT directory at ~/gmt_local_files not existing.  The existing code silently created the directory, which was empty, of course, hence the error.  Added logging and print to warn when creating the directory.
